apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-ipamd
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/veekaly/sample-krew/releases/download/v0.1.0/kubectl-ipamd_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-ipamd"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-ipamd"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/veekaly/sample-krew/releases/download/v0.1.0/kubectl-ipamd_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-ipamd"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-ipamd"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/veekaly/sample-krew/releases/download/v0.1.0/kubectl-ipamd_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-ipamd.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-ipamd.exe"
  shortDescription: A new plugin
  homepage: https://github.com/veekaly/sample-krew
  caveats: |
    Usage:
      $ kubectl kubectl-ipamd

    For additional options:
      $ kubectl kubectl-ipamd --help
      or https://github.com/veekaly/sample-krew/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
